version: '3.4'

services:
  eventstore:
    image: eventstore/eventstore:release-4.0.2
    ports:
      - "2113:2113"
      - "1113:1113"
    environment:
      - RUN_PROJECTIONS=All
    networks:
      - leanda-net

  redis:
    image: redis:4-alpine
    command: redis-server --appendonly yes
    ports:
      - "6379:6379"
    networks:
      - leanda-net

  rabbitmq:
    image: leanda/rabbitmq
    hostname: "leanda"
    environment:
      - RABBITMQ_DEFAULT_VHOST=leanda
    ports:
      - "8282:15672"
      - "5672:5672"
    networks:
      - leanda-net

  mongo:
    image: mongo:3.6
    ports:
      - "27017:27017"
    networks:
      - leanda-net

  imaging:
    container_name: imaging
    image: leanda/imaging:${TAG_VERSION-latest}
    entrypoint: /bin/bash
    environment:
      - OSDR_LOG_FOLDER=/logs
      - OSDR_TEMP_FILES_FOLDER=/temp
      - OSDR_RABBIT_MQ=rabbitmq://guest:guest@rabbitmq:5672/leanda
      - OSDR_MONGO_DB=mongodb://mongo:27017/osdr_dev
      - QUEUE_PREFETCH_SIZE=9
      - EXECUTOR_THREAD_COUNT=3
    command: ./wait-for-it.sh rabbitmq:5672 -t 60 -- java -Djava.awt.headless=true -Xmx256m -XX:NativeMemoryTracking=summary -jar sds-imaging-service.jar
    volumes:
      - ${OSDR_LOG_FOLDER}:/logs
      - ${OSDR_TEMP_FILES_FOLDER}:/temp
    networks:
      - leanda-net
    depends_on:
      - rabbitmq
      - mongo

  chemical-file-parser:
    container_name: chemical-file-parser
    image: leanda/chemical-file-parser:${TAG_VERSION-latest}
    entrypoint: /bin/bash
    environment:
      - TZ=EST
      - OSDR_LOG_FOLDER=/logs
      - OSDR_TEMP_FILES_FOLDER=/temp
      - OSDR_RABBIT_MQ=rabbitmq://guest:guest@rabbitmq:5672/leanda
      - OSDR_MONGO_DB=mongodb://mongo:27017/osdr_dev
      - QUEUE_PREFETCH_SIZE=9
      - EXECUTOR_THREAD_COUNT=3
    command: ./wait-for-it.sh rabbitmq:5672 -t 60 -- ./wait-for-it.sh mongo:27017 -t 60 -- java -jar chemical-parser.jar
    volumes:
      - ${OSDR_LOG_FOLDER}:/logs
      - ${OSDR_TEMP_FILES_FOLDER}:/temp
    networks:
      - leanda-net
    depends_on:
      - rabbitmq
      - mongo

  chemical-properties:
    container_name: chemical-properties
    image: leanda/chemical-properties:${TAG_VERSION-latest}
    entrypoint: /bin/bash
    environment:
      - TZ=EST
      - OSDR_LOG_FOLDER=/logs
      - OSDR_TEMP_FILES_FOLDER=/temp
      - OSDR_RABBIT_MQ=rabbitmq://guest:guest@rabbitmq:5672/leanda
      - OSDR_MONGO_DB=mongodb://mongo:27017/osdr_dev
      - QUEUE_PREFETCH_SIZE=9
      - EXECUTOR_THREAD_COUNT=3
    command: ./wait-for-it.sh rabbitmq:5672 -t 60 -- ./wait-for-it.sh mongo:27017 -t 60 -- java -jar sds-chemical-properties-service.jar
    volumes:
      - ${OSDR_LOG_FOLDER}:/logs
      - ${OSDR_TEMP_FILES_FOLDER}:/temp
    ports:
      - 8986:8086
    networks:
      - leanda-net
    depends_on:
      - rabbitmq
      - mongo

  metadata-processing:
    container_name: metadata-processing
    image: leanda/metadata-processing:${TAG_VERSION-latest}
    entrypoint: /bin/bash
    environment:
      - OSDR_LOG_FOLDER=/logs
      - OSDR_MONGO_DB=mongodb://mongo:27017/osdr
      - OSDR_RABBIT_MQ=rabbitmq://guest:guest@rabbitmq:5672/leanda
    command: ./wait-for-it.sh rabbitmq:5672 -t 60 -- ./Sds.MetadataStorage.Processing
    volumes:
      - ${OSDR_LOG_FOLDER}:/logs
    networks:
      - leanda-net
    ports:
      - "11050:11050"
    depends_on:
      - rabbitmq

  microscopy-metadata-service:
    container_name: microscopy-metadata
    image: leanda/microscopy-metadata:${TAG_VERSION-latest}
    entrypoint: /bin/bash
    environment:
      - TZ=EST
      - OSDR_LOG_FOLDER=/logs
      - OSDR_TEMP_FILES_FOLDER=/temp
      - OSDR_RABBIT_MQ=rabbitmq://guest:guest@rabbitmq:5672/leanda
      - OSDR_MONGO_DB=mongodb://mongo:27017/osdr_dev
      - QUEUE_PREFETCH_SIZE=9
      - EXECUTOR_THREAD_COUNT=3
    command: ./wait-for-it.sh rabbitmq:5672 -t 60 -- ./wait-for-it.sh mongo:27017 -t 60 -- java -XX:NativeMemoryTracking=summary -jar leanda-microscopy-metadata-service.jar
    volumes:
      - ${OSDR_LOG_FOLDER}:/logs/
      - ${OSDR_TEMP_FILES_FOLDER}:/temp/
    # ports:
    #   - 8986:8090
    networks:
      - leanda-net
    depends_on:
      - rabbitmq
      - mongo

  blob-storage-api:
    container_name: blob-storage-api
    image: leanda/blob-storage-webapi
    entrypoint: /bin/bash
    environment:
      - IDENTITY_SERVER_URL=${IDENTITY_SERVER_URL}
      - OSDR_LOG_FOLDER=/logs
      - OSDR_MONGO_DB=mongodb://mongo:27017/osdr
      - OSDR_RABBIT_MQ=rabbitmq://guest:guest@rabbitmq:5672/leanda
      - SWAGGER_BASEPATH=/blob/v1
      - OSDR_LOG_LEVEL=${OSDR_LOG_LEVEL}
    command: ./wait-for-it.sh rabbitmq:15672 -t 30 -- ./Sds.Storage.Blob.WebApi
    volumes:
      - ${OSDR_LOG_FOLDER}:/logs
    networks:
      - leanda-net
    ports:
      - "18006:18006"

  ui:
    container_name: ui
    image: leanda/ui:${TAG_VERSION-latest}
    environment:
      - IDENTITY_SERVER_URL=${IDENTITY_SERVER_URL}
      - CORE_API_URL=${CORE_API_URL}
      - BLOB_STORAGE_API_URL=${BLOB_STORAGE_API_URL}
      - IMAGING_URL=${IMAGING_URL}
      - SIGNALR_URL=${SIGNALR_URL}
      - METADATA_URL=${METADATA_URL}
      - PROXY_JSMOL_URL=${PROXY_JSMOL_URL}
      - KETCHER_URL=${KETCHER_URL}
      - REALM=${REALM}
    networks:
      - leanda-net
    ports:
      - "5555:80"
    depends_on:
      - blob-storage-api

networks:
  leanda-net:

#volumes:
#  test-results:
#    external: true
#    name: test-results